### PR TITLE
Replaced 'Unkown' typos

### PR DESCRIPTION
**Pull request by jgonyea**
This is just a simple grep/sed replace of all 'Unkown' or 'unkown' instances with the corrected spelling.

### CODE REVIEW

**Comment by JackWetson** [comment]
Hey @jgonyea , many thanks for this. I'm pretty sure (@Kivou-2000607 , please confirm :)). We'd need to generate new migration files and not just amend the old ones?

**Comment by jgonyea** [comment]
I wondered about that.  I can create new ones following the structure of other migration files within the migration folders

**Comment by JackWetson** [comment]
> I wondered about that. I can create new ones following the structure of other migration files within the migration folders

if you update the models and run `./manage.py makemigrations` this will do it automatically

**Comment by Kivou-2000607** [comment]
hoo yeah better not touch that here ^^

**Comment by Kivou-2000607** [comment]
but lol... I do love to misspell this one...

**Comment by jgonyea** [comment]
I'm going to close this PR and submit a fixed one.

**Pull request closed without merging**
